import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Provider } from './provider';
import Header from '@/components/common/Header/Header';
import { LayoutProps } from '@/types/layout';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout: React.FC<LayoutProps> = ({ children, showHeader = true }) => {
  // console.log('test', showHeader);
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>
          {showHeader && <Header />}
          {children}
        </Provider>
      </body>
    </html>
  );
};
export default RootLayout;
